### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by jansivans** [leonardoporro/Detached#11]
Exception is thrown when trying to run ASP.NET Core 2.0 app with this library:
![image](https://user-images.githubusercontent.com/5667073/31072922-93c858e8-a772-11e7-8420-c41e5ce3db6e.png)

**Comment by leonardoporro** [comment]
Thank you!. Going to fix it next weekend. I've been working in a better version of this library, so didn't test it with 2.0.

**Comment by naveedtejani** [comment]
@leonardoporro any update on it? :)
