### ISSUE TITLE
Issue with netcore 2.0

### ISSUE THREAD

**Issue by belpyro** [leonardoporro/Detached#13]
Could you please update your great solution to netcore 2.0? 
Because current version has issues with compatible.
Thank you!

**Comment by leonardoporro** [comment]
Sorry, I've been very busy with personal issues, but I'll try to do something. Thanks for writting.

**Comment by belpyro** [comment]
Hello, again.
I have updated several projects to .Net Core 2.0. You can get all needed changes in my  forked repository: https://github.com/belpyro/Detached.git
Thank you.

**Comment by skipper876** [comment]
@belpyro @leonardoporro Hey guys so I'm using the forked version from @belpyro in a .net core 2.0 project and I'm getting this warning: 
![service_provider_error](https://user-images.githubusercontent.com/5613369/39798611-d9afc372-5326-11e8-8925-af563e120a3a.jpg)

Any ideas on how to solve?

**Comment by MutatedTomato** [comment]
I have fixed some bugs and added some features using @belpyro 's fork while keeping the tests. Unfortunately, it is incompatible to EF Core 1.x because of the private API change.

https://github.com/MutatedTomato/Detached
