### ISSUE TITLE
Having multiple navigation properties to the same table results in incorrect EntityState for second property's children

### ISSUE THREAD

**Issue by stefan-stanca** [leonardoporro/Detached#5]
There seems to be an issue for the following graph:

class A
{
public int Id{get;set;}
[Owned]
public B B1{get;set;}
[Owned]
public B B2{get;set;}
}

class B
{
public int Id{get;set;}
[Owned]
public ICollection<C> C {get;set} <= these will be set to Added on B2
}

class C
{
public int Id {get;set;}
string Prop1{get;set;}
}
When doing dbContext.Set<A>.UpdateAsync(myAObject) , it is flagging the C elements in B1 as Added even though their Id properties are set.

**Comment by leonardoporro** [comment]
Thanks! I'll fix it asap.

**Comment by stefan-stanca** [comment]
I think the problem is that during UpdateAsync it is not loading the entire object graph from the context for A to compare with the detached object graph, resulting in an incomplete comparison.

**Comment by stefan-stanca** [comment]
I just tested  the same scenario for LoadAsync  and it is the same. It will load A.B1.C but will not load A.B2.C.

**Comment by leonardoporro** [comment]
I've added an unnecesary cycle check in LoadAsync (GetIncludePaths).
It's fixed in version 1.1.1, please check and let me know.
Just make sure you don't add [Owned] or [Associated] to a back reference navigation property (the one that points to the parent).

**Comment by leonardoporro** [comment]
And sorry for the delay! I had a lot of work from my job.

**Comment by stefan-stanca** [comment]
it seems ok now,  thanks for the quick response.

**Comment by leonardoporro** [comment]
Thanks for using it!
