### ISSUE TITLE
Multiple delete 

### ISSUE THREAD

**Issue by leonardoporro** [leonardoporro/Detached#6]
"Sending a list of Ids (long) to DeleteAsync throws the following exception "Object must implement IConvertible."
Casting the list to an object array I get the following "One or more errors occurred. (Key values count mismatch, expected Id)"

**Comment by leonardoporro** [comment]
use
`await detachedContext.Set<Entity>().DeleteAsync(new KeyValue(1), new KeyValue(2));`

**Comment by rupoase** [comment]
Hello Leonardo, 

I'm trying to use the DeteleAsync feature with the new syntax, like follows:

`await detachedContext.Set<Entity>().DeleteAsync(someEnumerable.Select(e=>e.Id).ToArray());` - this returns the IComparable error.
`await detachedContext.Set<Entity>().DeleteAsync(someEnumerable.Select(e=> new KeyValue(e.Id)).ToArray();` - this returns IndexOutOfRange exception.

I think I'm doing something wrong, but based on the parameter metadata that is showing up in the Intellisense, I can only figure out the above examples.
Can you write down an example of usage where the Entity is an actual complex object ?
Thank you!
