### ISSUE TITLE
Why reloading the entity again after updating?

### ISSUE THREAD

**Issue by cryo75** [leonardoporro/Detached#7]
First of all great job. I'm currently a user of GraphDiff and was planning to move to EF.Core once it's more mature like EF6. 

The code looks much more cleaner and easy to understand.

I have a couple of questions when Updating an entity.

1. Why are you reloading the root after persisting? Wouldn't EF.Core set the id's automatically?

2. Does Detached support 3 and more levels of nested tables?

3. I have a large entity spread among 20 tables and because the entity loaded piece by piece (depending on the user if he wants to load some particular details). So, on updating the entity, currently in GraphDiff I do:

`    
    //Root
    var updatedEntity = ((DbContext)dataContext).UpdateGraph<MyEntity> (entity, map => map.AssociatedEntity(x => x.Type)); //And all other mappings here

    //Detach it for now...
    var state = dataContext.GetEntry(abo).State;
    dataContext.GetEntry(abo).State = EntityState.Detached;

    //Save some child table which would have been loaded separately and attached to the entity 
    if (entity.Children?.Any() ?? true)
    {
        //This is a workaround because GraphDiff needs the id's
        entity.Children.ToList()
            .ForEach(x =>
            {
                x.EntityId = x.Id == 0 ? 0 : entity.Id;
                x.ForeignId = x.Foreign.Id;
             });

        //Save the children
        var temp = ((DbContext)dataContext).UpdateGraph<MyEntity>
            (entity, //Any mappings here...);

        //Attach updated children to the entity we just saved above
        foreach (var child in temp.Children)
        {
            updatedEntity.Children.Add(child);
        }

        //Detach the changed entity as this is just temporary
        dataContext.GetEntry(temp).State = EntityState.Detached;
    }

    //Do the same for other child tables

    //Re-attach the updated entity
    dataContext.GetEntry(updatedEntity).State = state;
    return updatedEntity;`

Would this workflow still be possible using Detached and maybe even simplified to improve performance because currently the whole save method with GraphDiff takes a few seconds to complete

**Comment by leonardoporro** [comment]
Hi @cryo75 , thanks for using and for the feedback.
About your questions:

1. I can't find the point where I am loading the entity again...
It works as GraphDiff, by loading the entity, comparing and updating as needed.
The updated entity is the one that was returned by UpdateAsync.
i.e.: 
persistedEntity = await context.Set<T>().UpdateAsync(detachedEntity);
(persisted entity is the one that was loaded from the DB, and merged with detachedEntity, after you call SaveChangesAsync, it will contains the generated fiels, like IDs. detachedEntity won't have).

2. It is recursive. At a first glance, I don't see a limit in nesting.

3. There is no mechanism to change what is owned (composition) and what is associated (association) right now. But there is no limit on what is the root (aggregate).
e.g.: if you have a tree like this:
GrandGrandParent
- GrandParent
-- Parent
--- Child
you can call UpdateAsync(GrandGrandParent) or UpdateAsync(GrandParent) or UpdateAsync(Parent)... at any level.

I will add an option to ignore fields later.

About performance, I did my best to integrate with EF Core, merge using dictionaries to avoid O(n2) operations and avoid loading relations beyond associations. 
But updating by comparison is a heavy process and I don't recommend it for large entities.

Thanks again and let me know if anything is not clear.
