### ISSUE TITLE
Multiple Associated Attribute properties in graph does not load correctly

### ISSUE THREAD

**Issue by stefan-stanca** [leonardoporro/Detached#8]
```
Given the following example

class One {
public long Id {get;set;}
[Associated]
public Two Two {get;set;}
}

class Two {
public long Id {get;set;}
[Associated] => changing this to [Owned] will load correctly
public Three Three {get;set;}
}

public class Three{
 public long Id {get;set;}
}

detachedContext.Set<One>().LoadAsync(some_id); => will not load One.Two.Three
```

**Comment by leonardoporro** [comment]
Hi @stefan-stanca,
By definition, I load n-levels of Owned properties and 1 level of Associated.
I did this to define the boundaries of the root or "aggregate" object, If I load nested associations I may end up loading a big tree, or even the entire DB.

I'm working on a new version that will expose the Set as IQueryable, so you can add your own includes if needed.

And I'm open to suggestions!

**Comment by stefan-stanca** [comment]
- I do not see the point in such a restriction. As a programmer, I get to decide in what manner to load objects with DetachedContext. If I dont want to load entire graphs of objects I can use use the Include/ThenInclude api on regular IQueryable and that really defeats the purpose of Detached,
- Setting it up with IQueryable would really be usefull as sometimes you may need to load entity graph for more than one object.
- Setting up my own includes would kind of defeat the purpose of this plugin, I can use Include for that.

**Comment by leonardoporro** [comment]
This is my understanding... but maybe I'm wrong...

Let's say I have an "Invoice" entity. The Invoice has [Owned]Rows, and an [Associated]Sell Point.
Sell point also has [Associated]Employees, and Employees have [Owned]Roles and Roles have... any other thing...
If I load associations recursively, I will end loading everything.
There are "main", "root", "strong" entities, called Aggregates in UML, like Invoice and Sell Point. And there are other "weak" entities like Row that have no meaning without the root.
A relation between a Strong and a Weak entity is a Composition (Owned). A relation between two Strong entities is an Association.
The idea behind the library is to update one Strong entity with its relations, but not two strong entities at the same time.
The Load method is used to get the persisted version (database) being used to match the detached version (deserialized). And it is exposed just as a tool to do that.

If you want to join two Strong entities, or project the results to some DTO, you should probably use a normal EF query, and there is no point in using the library.

I'm working now in adding the ability to persist not only entities but any DTO. It will make it more useful.
Will be available next week.
